debug: true
server.port: 8081

---
spring:
  config:
    activate:
      on-profile: first
my:
  props:
    prop3: prop3 first
    prop4:
      - prop4_0_yaml_first
      - prop4_1_yaml_first
      - prop4_2_yaml_first
---
spring:
  config:
    activate:
      on-profile: second
my:
  props:
    prop3: prop3 second
    prop4:
      - prop4_0_yaml_second
      - prop4_1_yaml_second
      - prop4_2_yaml_second
---
spring:
  config:
    activate:
      on-profile: third
my:
  props:
    prop3: prop3 third
    prop4:
      - prop4_0_yaml_third
      - prop4_1_yaml_third
      - prop4_2_yaml_third
