debug: true
server.port: 8081

---
spring:
  config:
    activate:
      on-profile: first
my:
  props:
    prop3: prop3 first
---
spring:
  config:
    activate:
      on-profile: second
my:
  props:
    prop3: prop3 second
---
spring:
  config:
    activate:
      on-profile: third
my:
  props:
    prop3: prop3 third
